<?php
/**
 * Settings for Moebel feeds
 */

function woogool_moebel_attributes() {

    $moebel = array(
        "Feed_fields" => array(
            'label' => 'Feed fields',
            'attributes' => array(
                "art_nr" => array(
                    'label' => 'Art nr',
                    "name" => "art_nr",
                    "feed_name" => "art_nr",
                    "format" => "required",
                    "woogool_suggest" => "id",
                ),
                "art_name" => array(
                    'label' => 'Art name',
                    "name" => "art_name",
                    "feed_name" => "art_name",
                    "format" => "required",
                    "woogool_suggest" => "title",
                ),
                "art_beschreibung" => array(
                    'label' => 'Art beschreibung',
                    "name" => "art_beschreibung",
                    "feed_name" => "art_beschreibung",
                    "format" => "required",
                    "woogool_suggest" => "description",
                ),
                "art_url" => array(
                    'label' => 'Art URL',
                    "name" => "art_url",
                    "feed_name" => "art_url",
                    "format" => "required",
                    "woogool_suggest" => "link",
                ),
                "art_img_url" => array(
                    'label' => 'Art img URL',
                    "name" => "art_img_url",
                    "feed_name" => "art_img_url",
                    "format" => "required",
                    "woogool_suggest" => "image",
                ),
                "art_waehrung" => array(
                    'label' => 'Art waehrung',
                    "name" => "art_waehrung",
                    "feed_name" => "art_waehrung",
                    "format" => "required",
                ),
                "art_price" => array(
                    'label' => 'Art preis',
                        "name" => "art_price",
                        "feed_name" => "art_price",
                        "format" => "required",
                        "woogool_suggest" => "price",
                ),
                "art_lieferkosten" => array(
                    'label' => 'Art lieferkosten',
                        "name" => "art_lieferkosten",
                        "feed_name" => "art_lieferkosten",
                        "format" => "required",
                ),
                "art_stamm" => array(
                    'label' => 'Art stamm',
                        "name" => "art_stamm",
                        "feed_name" => "art_stamm",
                        "format" => "optional",
                ),
                "art_ean" => array(
                    'label' => 'Art ean',
                        "name" => "art_ean",
                        "feed_name" => "art_ean",
                        "format" => "optional",
                ),
                "art_streichpreis" => array(
                    'label' => 'Art streichpreis',
                        "name" => "art_streichpreis",
                        "feed_name" => "art_streichpreis",
                        "format" => "optional",
                ),
                "art_grundpreis" => array(
                    'label' => 'Art grundpreis',
                        "name" => "art_grundpreis",
                        "feed_name" => "art_grundpreis",
                        "format" => "optional",
                ),
                "art_grundpreis_einheit" => array(
                    'label' => 'Art grundpreis einheit',
                        "name" => "art_grundpreis_einheit",
                        "feed_name" => "art_grundpreis_einheit",
                        "format" => "optional",
                ),
                "art_finanzierung" => array(
                    'label' => 'Art finanzierung',
                        "name" => "art_finanzierung",
                        "feed_name" => "art_finanzierung",
                        "format" => "optional",
                ),
                "art_lieferzeit" => array(
                    'label' => 'Art lieferzeit',
                        "name" => "art_lieferzeit",
                        "feed_name" => "art_lieferzeit",
                        "format" => "optional",
                ),
                "art_lieferzeit_wert" => array(
                    'label' => 'Art lieferzeit wert',
                        "name" => "art_lieferzeit_wert",
                        "feed_name" => "art_lieferzeit_wert",
                        "format" => "optional",
                ),
                "art_lieferkosten_text" => array(
                    'label' => 'Art lieferkosten text',
                        "name" => "art_lieferkosten_text",
                        "feed_name" => "art_lieferkosten_text",
                        "format" => "optional",
                ),
                "art_versand_at" => array(
                    'label' => 'Art versand at',
                        "name" => "art_versand_at",
                        "feed_name" => "art_versand_at",
                        "format" => "optional",
                ),
                "art_versand_at_preis" => array(
                    'label' => 'Art versand at preis',
                        "name" => "art_versand_at_preis",
                        "feed_name" => "art_versand_at_preis",
                        "format" => "optional",
                ),
                "art_versand_ch" => array(
                    'label' => 'Art versand ch',
                        "name" => "art_versand_ch",
                        "feed_name" => "art_versand_ch",
                        "format" => "optional",
                ),
                "art_versand_ch_preis" => array(
                    'label' => 'Art versand ch preis',
                        "name" => "art_versand_ch_preis",
                        "feed_name" => "art_versand_ch_preis",
                        "format" => "optional",
                ),
                "art_versand_sonstlaender" => array(
                    'label' => 'Art versand sonstlaender',
                        "name" => "art_versand_sonstlaender",
                        "feed_name" => "art_versand_sonstlaender",
                        "format" => "optional",
                ),
                "art_montage" => array(
                    'label' => 'Art montage',
                        "name" => "art_montage",
                        "feed_name" => "art_montage",
                        "format" => "optional",
                ),
                "art_montagepreis" => array(
                    'label' => 'Art montagepreis',
                        "name" => "art_montagepreis",
                        "feed_name" => "art_montagepreis",
                        "format" => "optional",
                ),
                "art_express" => array(
                    'label' => 'Art express',
                        "name" => "art_express",
                        "feed_name" => "art_express",
                        "format" => "optional",
                ),
                "art_verfuegbarkeit" => array(
                    'label' => 'Art verfuegbarkeit',
                        "name" => "art_verfuegbarkeit",
                        "feed_name" => "art_verfuegbarkeit",
                        "format" => "optional",
                ),
                "art_verfuegbarkeit" => array(
                    'label' => 'Art verfuegbarkeit',
                        "name" => "art_verfuegbarkeit",
                        "feed_name" => "art_verfuegbarkeit",
                        "format" => "optional",
                ),
                "art_farbe" => array(
                    'label' => 'Art farbe',
                        "name" => "art_farbe",
                        "feed_name" => "art_farbe",
                        "format" => "optional",
                ),
                "art_hauptfarbe" => array(
                    'label' => 'Art hauptfarbe',
                        "name" => "art_hauptfarbe",
                        "feed_name" => "art_hauptfarbe",
                        "format" => "optional",
                ),
                "art_material" => array(
                    'label' => 'Art material',
                        "name" => "art_material",
                        "feed_name" => "art_material",
                        "format" => "optional",
                ),
                "art_hauptmaterial" => array(
                    'label' => 'Art hauptmaterial',
                        "name" => "art_hauptmaterial",
                        "feed_name" => "art_hauptmaterial",
                        "format" => "optional",
                ),
                "art_holzart" => array(
                    'label' => 'Art holzart',
                        "name" => "art_holzart",
                        "feed_name" => "art_holzart",
                        "format" => "optional",
                ),
                "art_stil" => array(
                    'label' => 'Art stil',
                        "name" => "art_stil",
                        "feed_name" => "art_stil",
                        "format" => "optional",
                ),
                "art_marke" => array(
                    'label' => 'Art marke',
                        "name" => "art_marke",
                        "feed_name" => "art_marke",
                        "format" => "optional",
                ),
                "art_kategorie" => array(
                    'label' => 'Art kategorie',
                        "name" => "art_kategorie",
                        "feed_name" => "art_kategorie",
                        "format" => "optional",
                ),
                "art_bewertung" => array(
                    'label' => 'Art bewertung',
                        "name" => "art_bewertung",
                        "feed_name" => "art_bewertung",
                        "format" => "optional",
                ),
                "art_bewertungsanzahl" => array(
                    'label' => 'Art bewertungsanzahl',
                        "name" => "art_bewertungsanzahl",
                        "feed_name" => "art_bewertungsanzahl",
                        "format" => "optional",
                ),
                "art_extras" => array(
                    'label' => 'Art extras',
                        "name" => "art_extras",
                        "feed_name" => "art_extras",
                        "format" => "optional",
                ),
                "art_geschlecht" => array(
                    'label' => 'Art geschlecht',
                        "name" => "art_geschlecht",
                        "feed_name" => "art_geschlecht",
                        "format" => "optional",
                ),
                "art_oberflaeche" => array(
                    'label' => 'Art oberflaeche',
                        "name" => "art_oberflaeche",
                        "feed_name" => "art_oberflaeche",
                        "format" => "optional",
                ),
                "art_sets" => array(
                    'label' => 'Art sets',
                        "name" => "art_sets",
                        "feed_name" => "art_sets",
                        "format" => "optional",
                ),
                "art_ausrichtung" => array(
                    'label' => 'Art ausrichting',
                        "name" => "art_ausrichtung",
                        "feed_name" => "art_ausrichting",
                        "format" => "optional",
                ),
                "art_verwendungsort" => array(
                    'label' => 'Art verwendungsort',
                        "name" => "art_verwendungsort",
                        "feed_name" => "art_verwendungsort",
                        "format" => "optional",
                ),
                "art_sitzplatze" => array(
                    'label' => 'Art sitzplatze',
                        "name" => "art_sitzplatze",
                        "feed_name" => "art_sitzplatze",
                        "format" => "optional",
                ),
                "art_muster" => array(
                    'label' => 'Art muster',
                        "name" => "art_muster",
                        "feed_name" => "art_muster",
                        "format" => "optional",
                ),
                "art_energiequelle" => array(
                    'label' => 'Art energiequelle',
                        "name" => "art_energiequelle",
                        "feed_name" => "art_energiequelle",
                        "format" => "optional",
                ),
                "art_siegel" => array(
                    'label' => 'Art siegel',
                        "name" => "art_siegel",
                        "feed_name" => "art_siegel",
                        "format" => "optional",
                ),
                "art_hersteller" => array(
                    'label' => 'Art hersteller',
                        "name" => "art_hersteller",
                        "feed_name" => "art_hersteller",
                        "format" => "optional",
                ),
                "art_img_url2" => array(
                    'label' => 'Art img url2',
                        "name" => "art_img_url2",
                        "feed_name" => "art_img_url2",
                        "format" => "optional",
                ),
                "art_img_url3" => array(
                    'label' => 'Art img url3',
                        "name" => "art_img_url3",
                        "feed_name" => "art_img_url3",
                        "format" => "optional",
                ),
                "art_img_url4" => array(
                    'label' => 'Art img url4',
                        "name" => "art_img_url4",
                        "feed_name" => "art_img_url4",
                        "format" => "optional",
                ),
                "art_masse" => array(
                    'label' => 'Art masse',
                        "name" => "art_masse",
                        "feed_name" => "art_masse",
                        "format" => "optional",
                ),
                "art_breite" => array(
                    'label' => 'Art breite',
                        "name" => "art_breite",
                        "feed_name" => "art_breite",
                        "format" => "optional",
                ),
                "art_breite_einheit" => array(
                    'label' => 'Art breite einheit',
                        "name" => "art_breite_einheit",
                        "feed_name" => "art_breite_einheit",
                        "format" => "optional",
                ),
                "art_tiefe" => array(
                    'label' => 'Art tiefe',
                        "name" => "art_tiefe",
                        "feed_name" => "art_tiefe",
                        "format" => "optional",
                ),
                "art_tiefe_einheit" => array(
                    'label' => 'Art tiefe einheit',
                        "name" => "art_tiefe_einheit",
                        "feed_name" => "art_tiefe_einheit",
                        "format" => "optional",
                ),
                "art_hoehe" => array(
                    'label' => 'Art hoehe',
                        "name" => "art_hoehe",
                        "feed_name" => "art_hoehe",
                        "format" => "optional",
                ),
                "art_hoehe_einheit" => array(
                    'label' => 'Art hoehe einheit',
                        "name" => "art_hoehe_einheit",
                        "feed_name" => "art_hoehe_einheit",
                        "format" => "optional",
                ),
                "art_sitztiefe" => array(
                    'label' => 'Art sitztiefe',
                        "name" => "art_sitztiefe",
                        "feed_name" => "art_sitztiefe",
                        "format" => "optional",
                ),
                "art_sitzhoehe" => array(
                    'label' => 'Art sitzhoehe',
                        "name" => "art_sitzhoehe",
                        "feed_name" => "art_sitzhoehe",
                        "format" => "optional",
                ),
                "art_sitzhoehe_einheit" => array(
                    'label' => 'Art sitzhoehe einheit',
                        "name" => "art_sitzhoehe_einheit",
                        "feed_name" => "art_sitzhoehe_einheit",
                        "format" => "optional",
                ),
                "art_sitztiefe_einheit" => array(
                    'label' => 'Art sitztiefe einheit',
                        "name" => "art_sitztiefe_einheit",
                        "feed_name" => "art_sitztiefe_einheit",
                        "format" => "optional",
                ),
                "art_schenkelmass" => array(
                    'label' => 'Art schenkelmass',
                        "name" => "art_schenkelmass",
                        "feed_name" => "art_schenkelmass",
                        "format" => "optional",
                ),
                "art_schenkelmass_einheit" => array(
                    'label' => 'Art schenkelmass einheit',
                        "name" => "art_schenkelmass_einheit",
                        "feed_name" => "art_schenkelmass_einheit",
                        "format" => "optional",
                ),
                "art_durchmesser" => array(
                    'label' => 'Art durchmesser',
                        "name" => "art_durchmesser",
                        "feed_name" => "art_durchmesser",
                        "format" => "optional",
                ),
                "art_durchmesser_einheit" => array(
                    'label' => 'Art durchmesser einheit',
                        "name" => "art_durchmesser_einheit",
                        "feed_name" => "art_durchmesser_einheit",
                        "format" => "optional",
                ),
                "art_aufhaengung" => array(
                    'label' => 'Art aufhaengung',
                        "name" => "art_aufhaengung",
                        "feed_name" => "art_aufhaengung",
                        "format" => "optional",
                ),
                "art_fuellmaterial" => array(
                    'label' => 'Art fuellmaterial',
                        "name" => "art_fuellmaterial",
                        "feed_name" => "art_fuellmaterial",
                        "format" => "optional",
                ),
                "art_funktion_heimtext" => array(
                    'label' => 'Art funktion heimtex',
                        "name" => "art_funktion_heimtext",
                        "feed_name" => "art_funtion_heimtext",
                        "format" => "optional",
                ),
                "art_effizienzklasse" => array(
                    'label' => 'Art effizienzklasse',
                        "name" => "art_effizienzklasse",
                        "feed_name" => "art_effizienzklasse",
                        "format" => "optional",
                ),
                "art_lautstaerke" => array(
                    'label' => 'Art lautstaerke',
                        "name" => "art_lautstaerke",
                        "feed_name" => "art_lautstaerke",
                        "format" => "optional",
                ),
                "art_helligkeit" => array(
                    'label' => 'Art helligkeit',
                        "name" => "art_helligkeit",
                        "feed_name" => "art_helligkeit",
                        "format" => "optional",
                ),
                "art_lichtfarbe" => array(
                    'label' => 'Art lichtfarbe',
                        "name" => "art_lichtfarbe",
                        "feed_name" => "art_lichtfarbe",
                        "format" => "optional",
                ),
                "art_kuechenelektro" => array(
                    'label' => 'Art kuechenelektro',
                        "name" => "art_kuechenelektro",
                        "feed_name" => "art_kuechenelektro",
                        "format" => "optional",
                ),
                "art_herdeigenschaften" => array(
                    'label' => 'Art herdeigenschaften',
                        "name" => "art_herdeigenschaften",
                        "feed_name" => "art_herdeigenschaften",
                        "format" => "optional",
                ),
                "art_kochfeld" => array(
                    'label' => 'Art kochfeld',
                        "name" => "art_kochfeld",
                        "feed_name" => "art_kochfeld",
                        "format" => "optional",
                ),
                "art_material_arbeitsplatte" => array(
                    'label' => 'Art material arbeitsplatte',
                        "name" => "art_material_arbeitsplatte",
                        "feed_name" => "art_material_arbeitsplatte",
                        "format" => "optional",
                ),
                "art_extras_sessel" => array(
                    'label' => 'Art extras sessel',
                        "name" => "art_extras_sessel",
                        "feed_name" => "art_extras_sessel",
                        "format" => "optional",
                ),
                "art_schlaffunktion" => array(
                    'label' => 'Art schlaffunktion',
                        "name" => "art_schlaffunktion",
                        "feed_name" => "art_schlaffunktion",
                        "format" => "optional",
                ),
                "art_form_sofa" => array(
                    'label' => 'Art form sofa',
                        "name" => "art_form_sofa",
                        "feed_name" => "art_form_sofa",
                        "format" => "optional",
                ),
                "art_extras_sofa" => array(
                    'label' => 'Art extras sofa',
                        "name" => "art_extras_sofa",
                        "feed_name" => "art_extras_sofa",
                        "format" => "optional",
                ),
                "art_material_fuesse" => array(
                    'label' => 'Art material fuesse',
                        "name" => "art_material_fuesse",
                        "feed_name" => "art_material_fuesse",
                        "format" => "optional",
                ),
                "art_haertegrad_matratze" => array(
                    'label' => 'Art haertegrad matratze',
                        "name" => "art_haertegrad_matratze",
                        "feed_name" => "art_haertegrad_matratze",
                        "format" => "optional",
                ),
                "art_liegezonen" => array(
                    'label' => 'Art liegezonen',
                        "name" => "art_liegezonen",
                        "feed_name" => "art_liegezonen",
                        "format" => "optional",
                ),
                "art_allergiker_matratze" => array(
                    'label' => 'Art allergiker matratze',
                        "name" => "art_allergiker_matratze",
                        "feed_name" => "art_allergiker_matratze",
                        "format" => "optional",
                ),
                "art_stauraum_bett" => array(
                    'label' => 'Art stauraum bett',
                        "name" => "art_stauraum_bett",
                        "feed_name" => "art_stauraum_bett",
                        "format" => "optional",
                ),
                "art_beleuchtung_bett" => array(
                    'label' => 'Art beleuchtung bett',
                        "name" => "art_beleuchtung_bett",
                        "feed_name" => "art_beleuchtung_bett",
                        "format" => "optional",
                ),
                "art_matratzenmasse" => array(
                    'label' => 'Art matratzenmasse',
                        "name" => "art_matratzenmasse",
                        "feed_name" => "art_matratzenmasse",
                        "format" => "optional",
                ),
                "art_matratzenart" => array(
                    'label' => 'Art matratzenart',
                        "name" => "art_matratzenart",
                        "feed_name" => "art_matratzenart",
                        "format" => "optional",
                ),
                "art_bezugwaschbar" => array(
                    'label' => 'Art bezugwaschbar',
                        "name" => "art_bezugwaschbar",
                        "feed_name" => "art_bezugwaschbar",
                        "format" => "optional",
                ),
                "art_vitrine" => array(
                    'label' => 'Art vitrine',
                        "name" => "art_vitrine",
                        "feed_name" => "art_vitrine",
                        "format" => "optional",
                ),
                "art_abschliessbar" => array(
                    'label' => 'Art abschliessbar',
                        "name" => "art_abschliessbar",
                        "feed_name" => "art_abschliessbar",
                        "format" => "optional",
                ),
                "art_variable_faecher" => array(
                    'label' => 'Art variable faecher',
                        "name" => "art_variable_faecher",
                        "feed_name" => "art_variable_faecher",
                        "format" => "optional",
                ),
                "art_tuerenzahl" => array(
                    'label' => 'Art tuerenzahl',
                        "name" => "art_tuerenzahl",
                        "feed_name" => "art_tuerenzahl",
                        "format" => "optional",
                ),
                "art_schubladenzahl" => array(
                    'label' => 'Art schubladenzahl',
                        "name" => "art_schubladenzahl",
                        "feed_name" => "art_schubladenzahl",
                        "format" => "optional",
                ),
                "art_faecherzahl" => array(
                    'label' => 'Art faecherzahl',
                        "name" => "art_faecherzahl",
                        "feed_name" => "art_faecherzahl",
                        "format" => "optional",
                ),
                "art_tischform" => array(
                    'label' => 'Art tischform',
                        "name" => "art_tischform",
                        "feed_name" => "art_tischform",
                        "format" => "optional",
                ),
                "art_tischfunktion" => array(
                    'label' => 'Art tischfunktion',
                        "name" => "art_tischfunktion",
                        "feed_name" => "art_tischfunktion",
                        "format" => "optional",
                ),
                "art_gestell_material" => array(
                    'label' => 'Art gestell material',
                        "name" => "art_gestell_material",
                        "feed_name" => "art_gestell_material",
                        "format" => "optional",
                ),
            ),
        ),
    );
    return $moebel;
}
?>
